name: DCO Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: DCO Check
        uses: docker://ghcr.io/codfish/verify-dco:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
